// Generated by tools/build-scene-atlas.py. Do not edit by hand.
#pragma once

#include "render/ScenePacket.h"

#include <array>
#include <cstddef>
#include <cstdint>

namespace rocket {

struct SceneAtlasPage {
    const char* key = nullptr;
    const char* relativePath = nullptr;
    std::uint16_t width = 0;
    std::uint16_t height = 0;
};

struct SceneAtlasFrame {
    std::uint8_t page = 0;
    std::uint16_t x = 0;
    std::uint16_t y = 0;
    std::uint16_t width = 0;
    std::uint16_t height = 0;
};

struct SceneAtlasTexture {
    std::uint16_t sourceWidth = 0;
    std::uint16_t sourceHeight = 0;
    std::uint16_t frameWidth = 0;
    std::uint16_t frameHeight = 0;
    std::uint16_t firstFrame = 0;
    std::uint8_t columns = 0;
    std::uint8_t rows = 0;
    std::uint8_t frameCount = 0;
};

inline constexpr std::array<SceneAtlasPage, 5U> kSceneAtlasPages {{
    {"scene_atlas_0", "assets/scene-atlas/scene-atlas-0.png", 3710U, 3764U},
    {"scene_atlas_1", "assets/scene-atlas/scene-atlas-1.png", 3774U, 3774U},
    {"scene_atlas_2", "assets/scene-atlas/scene-atlas-2.png", 3774U, 3774U},
    {"scene_atlas_3", "assets/scene-atlas/scene-atlas-3.png", 3776U, 3724U},
    {"scene_atlas_4", "assets/scene-atlas/scene-atlas-4.png", 3696U, 3696U},
}};

inline constexpr std::array<SceneAtlasFrame, 696U>
    kSceneAtlasFrames {{
    {0U, 3047U, 518U, 512U, 512U}, // TextureId::Earth frame 0
    {3U, 3090U, 1034U, 512U, 512U}, // TextureId::Moon frame 0
    {0U, 2800U, 1550U, 512U, 512U}, // TextureId::Mars frame 0
    {2U, 2288U, 2518U, 1024U, 1024U}, // TextureId::RocketClosed frame 0
    {4U, 266U, 134U, 128U, 128U}, // TextureId::Explosion frame 0
    {4U, 398U, 134U, 128U, 128U}, // TextureId::Explosion frame 1
    {4U, 530U, 134U, 128U, 128U}, // TextureId::Explosion frame 2
    {4U, 662U, 134U, 128U, 128U}, // TextureId::Explosion frame 3
    {4U, 794U, 134U, 128U, 128U}, // TextureId::Explosion frame 4
    {4U, 926U, 134U, 128U, 128U}, // TextureId::Explosion frame 5
    {4U, 1058U, 134U, 128U, 128U}, // TextureId::Explosion frame 6
    {4U, 1190U, 134U, 128U, 128U}, // TextureId::Explosion frame 7
    {4U, 1322U, 134U, 128U, 128U}, // TextureId::Thrust frame 0
    {4U, 1454U, 134U, 128U, 128U}, // TextureId::Thrust frame 1
    {4U, 1586U, 134U, 128U, 128U}, // TextureId::Thrust frame 2
    {4U, 1718U, 134U, 128U, 128U}, // TextureId::Thrust frame 3
    {4U, 1850U, 134U, 128U, 128U}, // TextureId::Thrust frame 4
    {4U, 1982U, 134U, 128U, 128U}, // TextureId::Thrust frame 5
    {3U, 2058U, 1098U, 512U, 512U}, // TextureId::MiningDrone frame 0
    {0U, 3448U, 3302U, 112U, 112U}, // TextureId::DrillBit frame 0
    {0U, 3448U, 3418U, 112U, 112U}, // TextureId::DrillBit frame 1
    {0U, 2642U, 3650U, 112U, 112U}, // TextureId::DrillBit frame 2
    {0U, 1222U, 1926U, 112U, 112U}, // TextureId::DrillBit frame 3
    {0U, 1338U, 1926U, 112U, 112U}, // TextureId::DrillBit frame 4
    {3U, 2970U, 582U, 112U, 112U}, // TextureId::DrillBit frame 5
    {3U, 1030U, 2U, 1024U, 576U}, // TextureId::LocalSolarBackground frame 0
    {3U, 2058U, 2U, 1024U, 576U}, // TextureId::LocalSolarBackground frame 1
    {3U, 1030U, 582U, 1024U, 576U}, // TextureId::LocalSolarBackground frame 2
    {3U, 2U, 1030U, 1024U, 576U}, // TextureId::LocalSolarBackground frame 3
    {0U, 2800U, 2066U, 512U, 512U}, // TextureId::Mercury frame 0
    {3U, 1546U, 1614U, 512U, 512U}, // TextureId::Venus frame 0
    {0U, 2800U, 1034U, 512U, 512U}, // TextureId::Jupiter frame 0
    {3U, 2574U, 1550U, 512U, 512U}, // TextureId::Saturn frame 0
    {3U, 3090U, 1550U, 512U, 512U}, // TextureId::Uranus frame 0
    {3U, 1030U, 1162U, 512U, 512U}, // TextureId::Neptune frame 0
    {2U, 2U, 2518U, 1254U, 1254U}, // TextureId::ArkOperational frame 0
    {2U, 2U, 1260U, 1254U, 1254U}, // TextureId::ArkDamaged frame 0
    {1U, 2518U, 2U, 1254U, 1254U}, // TextureId::OuterPlanet01 frame 0
    {1U, 2U, 1260U, 1254U, 1254U}, // TextureId::OuterPlanet02 frame 0
    {1U, 2U, 2518U, 1254U, 1254U}, // TextureId::OuterPlanet03 frame 0
    {1U, 1260U, 1260U, 1254U, 1254U}, // TextureId::OuterPlanet04 frame 0
    {1U, 2518U, 1260U, 1254U, 1254U}, // TextureId::OuterPlanet05 frame 0
    {1U, 1260U, 2518U, 1254U, 1254U}, // TextureId::OuterPlanet06 frame 0
    {1U, 2518U, 2518U, 1254U, 1254U}, // TextureId::OuterPlanet07 frame 0
    {2U, 2U, 2U, 1254U, 1254U}, // TextureId::OuterPlanet08 frame 0
    {2U, 1260U, 2U, 1254U, 1254U}, // TextureId::OuterPlanet09 frame 0
    {3U, 2U, 2U, 1024U, 1024U}, // TextureId::RocketOpen frame 0
    {3U, 3086U, 518U, 512U, 512U}, // TextureId::MiniDroneMining frame 0
    {3U, 2058U, 582U, 512U, 512U}, // TextureId::MiniDroneResource frame 0
    {3U, 2574U, 1034U, 512U, 512U}, // TextureId::MiniDroneSurvey frame 0
    {3U, 3086U, 2U, 512U, 512U}, // TextureId::MiniDroneHazard frame 0
    {0U, 2800U, 2582U, 512U, 512U}, // TextureId::MiniDroneAttack frame 0
    {0U, 2800U, 3098U, 512U, 512U}, // TextureId::MiniDroneDefense frame 0
    {2U, 1260U, 2518U, 1024U, 1024U}, // TextureId::HeroicCapybara frame 0
    {0U, 1542U, 870U, 1254U, 1254U}, // TextureId::JetpackCapybara frame 0
    {3U, 2U, 1610U, 512U, 512U}, // TextureId::PoiGuidanceArrow frame 0
    {0U, 3047U, 2U, 512U, 512U}, // TextureId::Asteroid frame 0
    {0U, 1222U, 2U, 1821U, 864U}, // TextureId::FlightInstrumentCluster frame 0
    {0U, 2010U, 3386U, 128U, 128U}, // TextureId::EnemyAntNeutral frame 0
    {0U, 2142U, 3386U, 128U, 128U}, // TextureId::EnemyAntNeutral frame 1
    {0U, 2274U, 3386U, 128U, 128U}, // TextureId::EnemyAntNeutral frame 2
    {0U, 2406U, 3386U, 128U, 128U}, // TextureId::EnemyAntNeutral frame 3
    {0U, 3316U, 1034U, 128U, 128U}, // TextureId::EnemyAntNeutral frame 4
    {0U, 1222U, 870U, 128U, 128U}, // TextureId::EnemyAntNeutral frame 5
    {0U, 1354U, 870U, 128U, 128U}, // TextureId::EnemyAntNeutral frame 6
    {0U, 1222U, 1002U, 128U, 128U}, // TextureId::EnemyAntNeutral frame 7
    {0U, 1354U, 1002U, 128U, 128U}, // TextureId::EnemyAntNeutral frame 8
    {0U, 1222U, 1134U, 128U, 128U}, // TextureId::EnemyAntNeutral frame 9
    {0U, 1354U, 1134U, 128U, 128U}, // TextureId::EnemyAntNeutral frame 10
    {0U, 1222U, 1266U, 128U, 128U}, // TextureId::EnemyAntNeutral frame 11
    {0U, 1354U, 1266U, 128U, 128U}, // TextureId::EnemyAntNeutral frame 12
    {0U, 1222U, 1398U, 128U, 128U}, // TextureId::EnemyAntNeutral frame 13
    {0U, 1354U, 1398U, 128U, 128U}, // TextureId::EnemyAntNeutral frame 14
    {0U, 1222U, 1530U, 128U, 128U}, // TextureId::EnemyAntNeutral frame 15
    {0U, 1354U, 1530U, 128U, 128U}, // TextureId::EnemyAntNeutral frame 16
    {0U, 1222U, 1662U, 128U, 128U}, // TextureId::EnemyAntNeutral frame 17
    {0U, 1354U, 1662U, 128U, 128U}, // TextureId::EnemyAntNeutral frame 18
    {0U, 1222U, 1794U, 128U, 128U}, // TextureId::EnemyAntNeutral frame 19
    {0U, 2510U, 3614U, 128U, 128U}, // TextureId::EnemyAntLava frame 0
    {0U, 2642U, 3386U, 128U, 128U}, // TextureId::EnemyAntLava frame 1
    {0U, 2642U, 3518U, 128U, 128U}, // TextureId::EnemyAntLava frame 2
    {0U, 2774U, 3614U, 128U, 128U}, // TextureId::EnemyAntLava frame 3
    {0U, 2906U, 3614U, 128U, 128U}, // TextureId::EnemyAntLava frame 4
    {0U, 3038U, 3614U, 128U, 128U}, // TextureId::EnemyAntLava frame 5
    {0U, 3170U, 3614U, 128U, 128U}, // TextureId::EnemyAntLava frame 6
    {0U, 3302U, 3614U, 128U, 128U}, // TextureId::EnemyAntLava frame 7
    {0U, 3563U, 2U, 128U, 128U}, // TextureId::EnemyAntLava frame 8
    {0U, 3563U, 134U, 128U, 128U}, // TextureId::EnemyAntLava frame 9
    {0U, 3563U, 266U, 128U, 128U}, // TextureId::EnemyAntLava frame 10
    {0U, 3563U, 398U, 128U, 128U}, // TextureId::EnemyAntLava frame 11
    {0U, 3563U, 530U, 128U, 128U}, // TextureId::EnemyAntLava frame 12
    {0U, 3563U, 662U, 128U, 128U}, // TextureId::EnemyAntLava frame 13
    {0U, 3563U, 794U, 128U, 128U}, // TextureId::EnemyAntLava frame 14
    {0U, 3563U, 926U, 128U, 128U}, // TextureId::EnemyAntLava frame 15
    {0U, 1482U, 3386U, 128U, 128U}, // TextureId::EnemyAntLava frame 16
    {0U, 1614U, 3386U, 128U, 128U}, // TextureId::EnemyAntLava frame 17
    {0U, 1746U, 3386U, 128U, 128U}, // TextureId::EnemyAntLava frame 18
    {0U, 1878U, 3386U, 128U, 128U}, // TextureId::EnemyAntLava frame 19
    {0U, 2U, 3626U, 128U, 128U}, // TextureId::EnemyAntIce frame 0
    {0U, 134U, 3626U, 128U, 128U}, // TextureId::EnemyAntIce frame 1
    {0U, 266U, 3626U, 128U, 128U}, // TextureId::EnemyAntIce frame 2
    {0U, 398U, 3626U, 128U, 128U}, // TextureId::EnemyAntIce frame 3
    {0U, 530U, 3626U, 128U, 128U}, // TextureId::EnemyAntIce frame 4
    {0U, 662U, 3626U, 128U, 128U}, // TextureId::EnemyAntIce frame 5
    {0U, 794U, 3626U, 128U, 128U}, // TextureId::EnemyAntIce frame 6
    {0U, 926U, 3626U, 128U, 128U}, // TextureId::EnemyAntIce frame 7
    {0U, 1058U, 3626U, 128U, 128U}, // TextureId::EnemyAntIce frame 8
    {0U, 1190U, 3626U, 128U, 128U}, // TextureId::EnemyAntIce frame 9
    {0U, 2800U, 870U, 128U, 128U}, // TextureId::EnemyAntIce frame 10
    {0U, 1322U, 3614U, 128U, 128U}, // TextureId::EnemyAntIce frame 11
    {0U, 1454U, 3614U, 128U, 128U}, // TextureId::EnemyAntIce frame 12
    {0U, 1586U, 3614U, 128U, 128U}, // TextureId::EnemyAntIce frame 13
    {0U, 1718U, 3614U, 128U, 128U}, // TextureId::EnemyAntIce frame 14
    {0U, 1850U, 3614U, 128U, 128U}, // TextureId::EnemyAntIce frame 15
    {0U, 1982U, 3614U, 128U, 128U}, // TextureId::EnemyAntIce frame 16
    {0U, 2114U, 3614U, 128U, 128U}, // TextureId::EnemyAntIce frame 17
    {0U, 2246U, 3614U, 128U, 128U}, // TextureId::EnemyAntIce frame 18
    {0U, 2378U, 3614U, 128U, 128U}, // TextureId::EnemyAntIce frame 19
    {0U, 1354U, 1794U, 128U, 128U}, // TextureId::EnemyAntRadioactive frame 0
    {0U, 3448U, 1058U, 128U, 128U}, // TextureId::EnemyAntRadioactive frame 1
    {0U, 3316U, 1166U, 128U, 128U}, // TextureId::EnemyAntRadioactive frame 2
    {0U, 3580U, 1058U, 128U, 128U}, // TextureId::EnemyAntRadioactive frame 3
    {0U, 3448U, 1190U, 128U, 128U}, // TextureId::EnemyAntRadioactive frame 4
    {0U, 3316U, 1298U, 128U, 128U}, // TextureId::EnemyAntRadioactive frame 5
    {0U, 3580U, 1190U, 128U, 128U}, // TextureId::EnemyAntRadioactive frame 6
    {0U, 3448U, 1322U, 128U, 128U}, // TextureId::EnemyAntRadioactive frame 7
    {0U, 3316U, 1430U, 128U, 128U}, // TextureId::EnemyAntRadioactive frame 8
    {0U, 3580U, 1322U, 128U, 128U}, // TextureId::EnemyAntRadioactive frame 9
    {0U, 3448U, 1454U, 128U, 128U}, // TextureId::EnemyAntRadioactive frame 10
    {0U, 3316U, 1562U, 128U, 128U}, // TextureId::EnemyAntRadioactive frame 11
    {0U, 3580U, 1454U, 128U, 128U}, // TextureId::EnemyAntRadioactive frame 12
    {0U, 3448U, 1586U, 128U, 128U}, // TextureId::EnemyAntRadioactive frame 13
    {0U, 3316U, 1694U, 128U, 128U}, // TextureId::EnemyAntRadioactive frame 14
    {0U, 3580U, 1586U, 128U, 128U}, // TextureId::EnemyAntRadioactive frame 15
    {0U, 3448U, 1718U, 128U, 128U}, // TextureId::EnemyAntRadioactive frame 16
    {0U, 3316U, 1826U, 128U, 128U}, // TextureId::EnemyAntRadioactive frame 17
    {0U, 3580U, 1718U, 128U, 128U}, // TextureId::EnemyAntRadioactive frame 18
    {0U, 3448U, 1850U, 128U, 128U}, // TextureId::EnemyAntRadioactive frame 19
    {0U, 3316U, 1958U, 128U, 128U}, // TextureId::EnemyAntToxic frame 0
    {0U, 3580U, 1850U, 128U, 128U}, // TextureId::EnemyAntToxic frame 1
    {0U, 3448U, 1982U, 128U, 128U}, // TextureId::EnemyAntToxic frame 2
    {0U, 3316U, 2090U, 128U, 128U}, // TextureId::EnemyAntToxic frame 3
    {0U, 3580U, 1982U, 128U, 128U}, // TextureId::EnemyAntToxic frame 4
    {0U, 3448U, 2114U, 128U, 128U}, // TextureId::EnemyAntToxic frame 5
    {0U, 3316U, 2222U, 128U, 128U}, // TextureId::EnemyAntToxic frame 6
    {0U, 3580U, 2114U, 128U, 128U}, // TextureId::EnemyAntToxic frame 7
    {0U, 3448U, 2246U, 128U, 128U}, // TextureId::EnemyAntToxic frame 8
    {0U, 3316U, 2354U, 128U, 128U}, // TextureId::EnemyAntToxic frame 9
    {0U, 3580U, 2246U, 128U, 128U}, // TextureId::EnemyAntToxic frame 10
    {0U, 3448U, 2378U, 128U, 128U}, // TextureId::EnemyAntToxic frame 11
    {0U, 3316U, 2486U, 128U, 128U}, // TextureId::EnemyAntToxic frame 12
    {0U, 3580U, 2378U, 128U, 128U}, // TextureId::EnemyAntToxic frame 13
    {0U, 3448U, 2510U, 128U, 128U}, // TextureId::EnemyAntToxic frame 14
    {0U, 3316U, 2618U, 128U, 128U}, // TextureId::EnemyAntToxic frame 15
    {0U, 3580U, 2510U, 128U, 128U}, // TextureId::EnemyAntToxic frame 16
    {0U, 3448U, 2642U, 128U, 128U}, // TextureId::EnemyAntToxic frame 17
    {0U, 3316U, 2750U, 128U, 128U}, // TextureId::EnemyAntToxic frame 18
    {0U, 3580U, 2642U, 128U, 128U}, // TextureId::EnemyAntToxic frame 19
    {3U, 530U, 2666U, 128U, 128U}, // TextureId::EnemyFlyingNeutral frame 0
    {3U, 530U, 2798U, 128U, 128U}, // TextureId::EnemyFlyingNeutral frame 1
    {3U, 530U, 2930U, 128U, 128U}, // TextureId::EnemyFlyingNeutral frame 2
    {3U, 530U, 3062U, 128U, 128U}, // TextureId::EnemyFlyingNeutral frame 3
    {3U, 530U, 3194U, 128U, 128U}, // TextureId::EnemyFlyingNeutral frame 4
    {3U, 530U, 3326U, 128U, 128U}, // TextureId::EnemyFlyingNeutral frame 5
    {3U, 530U, 3458U, 128U, 128U}, // TextureId::EnemyFlyingNeutral frame 6
    {3U, 530U, 3590U, 128U, 128U}, // TextureId::EnemyFlyingNeutral frame 7
    {3U, 662U, 2666U, 128U, 128U}, // TextureId::EnemyFlyingNeutral frame 8
    {3U, 662U, 2798U, 128U, 128U}, // TextureId::EnemyFlyingNeutral frame 9
    {3U, 662U, 2930U, 128U, 128U}, // TextureId::EnemyFlyingNeutral frame 10
    {3U, 662U, 3062U, 128U, 128U}, // TextureId::EnemyFlyingNeutral frame 11
    {3U, 662U, 3194U, 128U, 128U}, // TextureId::EnemyFlyingNeutral frame 12
    {3U, 662U, 3326U, 128U, 128U}, // TextureId::EnemyFlyingNeutral frame 13
    {3U, 662U, 3458U, 128U, 128U}, // TextureId::EnemyFlyingNeutral frame 14
    {3U, 662U, 3590U, 128U, 128U}, // TextureId::EnemyFlyingNeutral frame 15
    {3U, 2246U, 2330U, 128U, 128U}, // TextureId::EnemyFlyingNeutral frame 16
    {3U, 1850U, 2406U, 128U, 128U}, // TextureId::EnemyFlyingNeutral frame 17
    {3U, 1982U, 2406U, 128U, 128U}, // TextureId::EnemyFlyingNeutral frame 18
    {3U, 2114U, 2406U, 128U, 128U}, // TextureId::EnemyFlyingNeutral frame 19
    {3U, 926U, 2470U, 128U, 128U}, // TextureId::EnemyFlyingLava frame 0
    {3U, 1058U, 2470U, 128U, 128U}, // TextureId::EnemyFlyingLava frame 1
    {3U, 1190U, 2470U, 128U, 128U}, // TextureId::EnemyFlyingLava frame 2
    {3U, 2498U, 2198U, 128U, 128U}, // TextureId::EnemyFlyingLava frame 3
    {3U, 2630U, 2198U, 128U, 128U}, // TextureId::EnemyFlyingLava frame 4
    {3U, 2762U, 2198U, 128U, 128U}, // TextureId::EnemyFlyingLava frame 5
    {3U, 2894U, 2198U, 128U, 128U}, // TextureId::EnemyFlyingLava frame 6
    {3U, 3026U, 2198U, 128U, 128U}, // TextureId::EnemyFlyingLava frame 7
    {3U, 3158U, 2198U, 128U, 128U}, // TextureId::EnemyFlyingLava frame 8
    {3U, 3290U, 2198U, 128U, 128U}, // TextureId::EnemyFlyingLava frame 9
    {3U, 3422U, 2246U, 128U, 128U}, // TextureId::EnemyFlyingLava frame 10
    {3U, 3554U, 2246U, 128U, 128U}, // TextureId::EnemyFlyingLava frame 11
    {3U, 398U, 2666U, 128U, 128U}, // TextureId::EnemyFlyingLava frame 12
    {3U, 398U, 2798U, 128U, 128U}, // TextureId::EnemyFlyingLava frame 13
    {3U, 398U, 2930U, 128U, 128U}, // TextureId::EnemyFlyingLava frame 14
    {3U, 398U, 3062U, 128U, 128U}, // TextureId::EnemyFlyingLava frame 15
    {3U, 398U, 3194U, 128U, 128U}, // TextureId::EnemyFlyingLava frame 16
    {3U, 398U, 3326U, 128U, 128U}, // TextureId::EnemyFlyingLava frame 17
    {3U, 398U, 3458U, 128U, 128U}, // TextureId::EnemyFlyingLava frame 18
    {3U, 398U, 3590U, 128U, 128U}, // TextureId::EnemyFlyingLava frame 19
    {3U, 266U, 2654U, 128U, 128U}, // TextureId::EnemyFlyingIce frame 0
    {3U, 266U, 2786U, 128U, 128U}, // TextureId::EnemyFlyingIce frame 1
    {3U, 266U, 2918U, 128U, 128U}, // TextureId::EnemyFlyingIce frame 2
    {3U, 266U, 3050U, 128U, 128U}, // TextureId::EnemyFlyingIce frame 3
    {3U, 266U, 3182U, 128U, 128U}, // TextureId::EnemyFlyingIce frame 4
    {3U, 266U, 3314U, 128U, 128U}, // TextureId::EnemyFlyingIce frame 5
    {3U, 266U, 3446U, 128U, 128U}, // TextureId::EnemyFlyingIce frame 6
    {3U, 266U, 3578U, 128U, 128U}, // TextureId::EnemyFlyingIce frame 7
    {3U, 2366U, 2198U, 128U, 128U}, // TextureId::EnemyFlyingIce frame 8
    {3U, 1850U, 2274U, 128U, 128U}, // TextureId::EnemyFlyingIce frame 9
    {3U, 1982U, 2274U, 128U, 128U}, // TextureId::EnemyFlyingIce frame 10
    {3U, 2114U, 2274U, 128U, 128U}, // TextureId::EnemyFlyingIce frame 11
    {3U, 1322U, 2394U, 128U, 128U}, // TextureId::EnemyFlyingIce frame 12
    {3U, 1454U, 2394U, 128U, 128U}, // TextureId::EnemyFlyingIce frame 13
    {3U, 1586U, 2394U, 128U, 128U}, // TextureId::EnemyFlyingIce frame 14
    {3U, 1718U, 2394U, 128U, 128U}, // TextureId::EnemyFlyingIce frame 15
    {3U, 794U, 2470U, 128U, 128U}, // TextureId::EnemyFlyingIce frame 16
    {3U, 398U, 2534U, 128U, 128U}, // TextureId::EnemyFlyingIce frame 17
    {3U, 530U, 2534U, 128U, 128U}, // TextureId::EnemyFlyingIce frame 18
    {3U, 662U, 2534U, 128U, 128U}, // TextureId::EnemyFlyingIce frame 19
    {3U, 1322U, 2526U, 128U, 128U}, // TextureId::EnemyFlyingRadioactive frame 0
    {3U, 1454U, 2526U, 128U, 128U}, // TextureId::EnemyFlyingRadioactive frame 1
    {3U, 1586U, 2526U, 128U, 128U}, // TextureId::EnemyFlyingRadioactive frame 2
    {3U, 1718U, 2526U, 128U, 128U}, // TextureId::EnemyFlyingRadioactive frame 3
    {3U, 794U, 2602U, 128U, 128U}, // TextureId::EnemyFlyingRadioactive frame 4
    {3U, 926U, 2602U, 128U, 128U}, // TextureId::EnemyFlyingRadioactive frame 5
    {3U, 1058U, 2602U, 128U, 128U}, // TextureId::EnemyFlyingRadioactive frame 6
    {3U, 1190U, 2602U, 128U, 128U}, // TextureId::EnemyFlyingRadioactive frame 7
    {3U, 2378U, 2330U, 128U, 128U}, // TextureId::EnemyFlyingRadioactive frame 8
    {3U, 2510U, 2330U, 128U, 128U}, // TextureId::EnemyFlyingRadioactive frame 9
    {3U, 2642U, 2330U, 128U, 128U}, // TextureId::EnemyFlyingRadioactive frame 10
    {3U, 2774U, 2330U, 128U, 128U}, // TextureId::EnemyFlyingRadioactive frame 11
    {3U, 2906U, 2330U, 128U, 128U}, // TextureId::EnemyFlyingRadioactive frame 12
    {3U, 3038U, 2330U, 128U, 128U}, // TextureId::EnemyFlyingRadioactive frame 13
    {3U, 3170U, 2330U, 128U, 128U}, // TextureId::EnemyFlyingRadioactive frame 14
    {3U, 3302U, 2378U, 128U, 128U}, // TextureId::EnemyFlyingRadioactive frame 15
    {3U, 3434U, 2378U, 128U, 128U}, // TextureId::EnemyFlyingRadioactive frame 16
    {3U, 3566U, 2378U, 128U, 128U}, // TextureId::EnemyFlyingRadioactive frame 17
    {3U, 794U, 2734U, 128U, 128U}, // TextureId::EnemyFlyingRadioactive frame 18
    {3U, 794U, 2866U, 128U, 128U}, // TextureId::EnemyFlyingRadioactive frame 19
    {3U, 794U, 2998U, 128U, 128U}, // TextureId::EnemyFlyingToxic frame 0
    {3U, 794U, 3130U, 128U, 128U}, // TextureId::EnemyFlyingToxic frame 1
    {3U, 794U, 3262U, 128U, 128U}, // TextureId::EnemyFlyingToxic frame 2
    {3U, 794U, 3394U, 128U, 128U}, // TextureId::EnemyFlyingToxic frame 3
    {3U, 794U, 3526U, 128U, 128U}, // TextureId::EnemyFlyingToxic frame 4
    {3U, 926U, 2734U, 128U, 128U}, // TextureId::EnemyFlyingToxic frame 5
    {3U, 926U, 2866U, 128U, 128U}, // TextureId::EnemyFlyingToxic frame 6
    {3U, 926U, 2998U, 128U, 128U}, // TextureId::EnemyFlyingToxic frame 7
    {3U, 926U, 3130U, 128U, 128U}, // TextureId::EnemyFlyingToxic frame 8
    {3U, 926U, 3262U, 128U, 128U}, // TextureId::EnemyFlyingToxic frame 9
    {3U, 926U, 3394U, 128U, 128U}, // TextureId::EnemyFlyingToxic frame 10
    {3U, 926U, 3526U, 128U, 128U}, // TextureId::EnemyFlyingToxic frame 11
    {3U, 1058U, 2734U, 128U, 128U}, // TextureId::EnemyFlyingToxic frame 12
    {3U, 1058U, 2866U, 128U, 128U}, // TextureId::EnemyFlyingToxic frame 13
    {3U, 1058U, 2998U, 128U, 128U}, // TextureId::EnemyFlyingToxic frame 14
    {3U, 1058U, 3130U, 128U, 128U}, // TextureId::EnemyFlyingToxic frame 15
    {3U, 1058U, 3262U, 128U, 128U}, // TextureId::EnemyFlyingToxic frame 16
    {3U, 1058U, 3394U, 128U, 128U}, // TextureId::EnemyFlyingToxic frame 17
    {3U, 1058U, 3526U, 128U, 128U}, // TextureId::EnemyFlyingToxic frame 18
    {3U, 1190U, 2734U, 128U, 128U}, // TextureId::EnemyFlyingToxic frame 19
    {2U, 3504U, 2782U, 128U, 128U}, // TextureId::EnemyBeetleNeutral frame 0
    {2U, 3636U, 2782U, 128U, 128U}, // TextureId::EnemyBeetleNeutral frame 1
    {2U, 3372U, 2914U, 128U, 128U}, // TextureId::EnemyBeetleNeutral frame 2
    {2U, 3504U, 2914U, 128U, 128U}, // TextureId::EnemyBeetleNeutral frame 3
    {2U, 3636U, 2914U, 128U, 128U}, // TextureId::EnemyBeetleNeutral frame 4
    {2U, 3372U, 3046U, 128U, 128U}, // TextureId::EnemyBeetleNeutral frame 5
    {2U, 3504U, 3046U, 128U, 128U}, // TextureId::EnemyBeetleNeutral frame 6
    {2U, 3636U, 3046U, 128U, 128U}, // TextureId::EnemyBeetleNeutral frame 7
    {2U, 3316U, 3178U, 128U, 128U}, // TextureId::EnemyBeetleNeutral frame 8
    {2U, 3316U, 3310U, 128U, 128U}, // TextureId::EnemyBeetleNeutral frame 9
    {2U, 3448U, 3178U, 128U, 128U}, // TextureId::EnemyBeetleNeutral frame 10
    {2U, 3580U, 3178U, 128U, 128U}, // TextureId::EnemyBeetleNeutral frame 11
    {2U, 3448U, 3310U, 128U, 128U}, // TextureId::EnemyBeetleNeutral frame 12
    {2U, 3580U, 3310U, 128U, 128U}, // TextureId::EnemyBeetleNeutral frame 13
    {2U, 3372U, 3442U, 128U, 128U}, // TextureId::EnemyBeetleNeutral frame 14
    {2U, 3372U, 3574U, 128U, 128U}, // TextureId::EnemyBeetleNeutral frame 15
    {2U, 3504U, 3442U, 128U, 128U}, // TextureId::EnemyBeetleNeutral frame 16
    {2U, 3636U, 3442U, 128U, 128U}, // TextureId::EnemyBeetleNeutral frame 17
    {2U, 3504U, 3574U, 128U, 128U}, // TextureId::EnemyBeetleNeutral frame 18
    {2U, 3636U, 3574U, 128U, 128U}, // TextureId::EnemyBeetleNeutral frame 19
    {2U, 1656U, 3546U, 128U, 128U}, // TextureId::EnemyBeetleLava frame 0
    {2U, 1788U, 3546U, 128U, 128U}, // TextureId::EnemyBeetleLava frame 1
    {2U, 1920U, 3546U, 128U, 128U}, // TextureId::EnemyBeetleLava frame 2
    {2U, 2052U, 3546U, 128U, 128U}, // TextureId::EnemyBeetleLava frame 3
    {2U, 2184U, 3546U, 128U, 128U}, // TextureId::EnemyBeetleLava frame 4
    {2U, 2316U, 3546U, 128U, 128U}, // TextureId::EnemyBeetleLava frame 5
    {2U, 2448U, 3546U, 128U, 128U}, // TextureId::EnemyBeetleLava frame 6
    {2U, 2580U, 3546U, 128U, 128U}, // TextureId::EnemyBeetleLava frame 7
    {2U, 2712U, 3546U, 128U, 128U}, // TextureId::EnemyBeetleLava frame 8
    {2U, 2844U, 3546U, 128U, 128U}, // TextureId::EnemyBeetleLava frame 9
    {2U, 2976U, 3546U, 128U, 128U}, // TextureId::EnemyBeetleLava frame 10
    {2U, 3108U, 3546U, 128U, 128U}, // TextureId::EnemyBeetleLava frame 11
    {2U, 3240U, 3546U, 128U, 128U}, // TextureId::EnemyBeetleLava frame 12
    {2U, 3372U, 2518U, 128U, 128U}, // TextureId::EnemyBeetleLava frame 13
    {2U, 3504U, 2518U, 128U, 128U}, // TextureId::EnemyBeetleLava frame 14
    {2U, 3636U, 2518U, 128U, 128U}, // TextureId::EnemyBeetleLava frame 15
    {2U, 3372U, 2650U, 128U, 128U}, // TextureId::EnemyBeetleLava frame 16
    {2U, 3504U, 2650U, 128U, 128U}, // TextureId::EnemyBeetleLava frame 17
    {2U, 3636U, 2650U, 128U, 128U}, // TextureId::EnemyBeetleLava frame 18
    {2U, 3372U, 2782U, 128U, 128U}, // TextureId::EnemyBeetleLava frame 19
    {0U, 3448U, 2774U, 128U, 128U}, // TextureId::EnemyBeetleIce frame 0
    {0U, 3316U, 2882U, 128U, 128U}, // TextureId::EnemyBeetleIce frame 1
    {0U, 3580U, 2774U, 128U, 128U}, // TextureId::EnemyBeetleIce frame 2
    {0U, 3448U, 2906U, 128U, 128U}, // TextureId::EnemyBeetleIce frame 3
    {0U, 3316U, 3014U, 128U, 128U}, // TextureId::EnemyBeetleIce frame 4
    {0U, 3580U, 2906U, 128U, 128U}, // TextureId::EnemyBeetleIce frame 5
    {0U, 3448U, 3038U, 128U, 128U}, // TextureId::EnemyBeetleIce frame 6
    {0U, 3316U, 3146U, 128U, 128U}, // TextureId::EnemyBeetleIce frame 7
    {0U, 3580U, 3038U, 128U, 128U}, // TextureId::EnemyBeetleIce frame 8
    {0U, 3448U, 3170U, 128U, 128U}, // TextureId::EnemyBeetleIce frame 9
    {0U, 3316U, 3278U, 128U, 128U}, // TextureId::EnemyBeetleIce frame 10
    {0U, 3580U, 3170U, 128U, 128U}, // TextureId::EnemyBeetleIce frame 11
    {0U, 3316U, 3410U, 128U, 128U}, // TextureId::EnemyBeetleIce frame 12
    {0U, 3434U, 3542U, 128U, 128U}, // TextureId::EnemyBeetleIce frame 13
    {0U, 3566U, 3302U, 128U, 128U}, // TextureId::EnemyBeetleIce frame 14
    {0U, 3566U, 3434U, 128U, 128U}, // TextureId::EnemyBeetleIce frame 15
    {0U, 3566U, 3566U, 128U, 128U}, // TextureId::EnemyBeetleIce frame 16
    {2U, 1260U, 3546U, 128U, 128U}, // TextureId::EnemyBeetleIce frame 17
    {2U, 1392U, 3546U, 128U, 128U}, // TextureId::EnemyBeetleIce frame 18
    {2U, 1524U, 3546U, 128U, 128U}, // TextureId::EnemyBeetleIce frame 19
    {3U, 3606U, 2U, 128U, 128U}, // TextureId::EnemyBeetleRadioactive frame 0
    {3U, 3606U, 134U, 128U, 128U}, // TextureId::EnemyBeetleRadioactive frame 1
    {3U, 3606U, 266U, 128U, 128U}, // TextureId::EnemyBeetleRadioactive frame 2
    {3U, 3606U, 398U, 128U, 128U}, // TextureId::EnemyBeetleRadioactive frame 3
    {3U, 3606U, 530U, 128U, 128U}, // TextureId::EnemyBeetleRadioactive frame 4
    {3U, 3606U, 662U, 128U, 128U}, // TextureId::EnemyBeetleRadioactive frame 5
    {3U, 3606U, 794U, 128U, 128U}, // TextureId::EnemyBeetleRadioactive frame 6
    {3U, 3606U, 926U, 128U, 128U}, // TextureId::EnemyBeetleRadioactive frame 7
    {3U, 3606U, 1058U, 128U, 128U}, // TextureId::EnemyBeetleRadioactive frame 8
    {3U, 3606U, 1190U, 128U, 128U}, // TextureId::EnemyBeetleRadioactive frame 9
    {3U, 3606U, 1322U, 128U, 128U}, // TextureId::EnemyBeetleRadioactive frame 10
    {3U, 3606U, 1454U, 128U, 128U}, // TextureId::EnemyBeetleRadioactive frame 11
    {3U, 3606U, 1586U, 128U, 128U}, // TextureId::EnemyBeetleRadioactive frame 12
    {3U, 3606U, 1718U, 128U, 128U}, // TextureId::EnemyBeetleRadioactive frame 13
    {3U, 3606U, 1850U, 128U, 128U}, // TextureId::EnemyBeetleRadioactive frame 14
    {3U, 3606U, 1982U, 128U, 128U}, // TextureId::EnemyBeetleRadioactive frame 15
    {3U, 2574U, 582U, 128U, 128U}, // TextureId::EnemyBeetleRadioactive frame 16
    {3U, 2574U, 714U, 128U, 128U}, // TextureId::EnemyBeetleRadioactive frame 17
    {3U, 2574U, 846U, 128U, 128U}, // TextureId::EnemyBeetleRadioactive frame 18
    {3U, 2706U, 582U, 128U, 128U}, // TextureId::EnemyBeetleRadioactive frame 19
    {3U, 2838U, 582U, 128U, 128U}, // TextureId::EnemyBeetleToxic frame 0
    {3U, 2706U, 714U, 128U, 128U}, // TextureId::EnemyBeetleToxic frame 1
    {3U, 2706U, 846U, 128U, 128U}, // TextureId::EnemyBeetleToxic frame 2
    {3U, 2838U, 714U, 128U, 128U}, // TextureId::EnemyBeetleToxic frame 3
    {3U, 2838U, 846U, 128U, 128U}, // TextureId::EnemyBeetleToxic frame 4
    {3U, 1546U, 1162U, 128U, 128U}, // TextureId::EnemyBeetleToxic frame 5
    {3U, 1546U, 1294U, 128U, 128U}, // TextureId::EnemyBeetleToxic frame 6
    {3U, 1546U, 1426U, 128U, 128U}, // TextureId::EnemyBeetleToxic frame 7
    {3U, 1678U, 1162U, 128U, 128U}, // TextureId::EnemyBeetleToxic frame 8
    {3U, 1810U, 1162U, 128U, 128U}, // TextureId::EnemyBeetleToxic frame 9
    {3U, 1678U, 1294U, 128U, 128U}, // TextureId::EnemyBeetleToxic frame 10
    {3U, 1678U, 1426U, 128U, 128U}, // TextureId::EnemyBeetleToxic frame 11
    {3U, 1810U, 1294U, 128U, 128U}, // TextureId::EnemyBeetleToxic frame 12
    {3U, 1810U, 1426U, 128U, 128U}, // TextureId::EnemyBeetleToxic frame 13
    {3U, 2062U, 1614U, 128U, 128U}, // TextureId::EnemyBeetleToxic frame 14
    {3U, 2194U, 1614U, 128U, 128U}, // TextureId::EnemyBeetleToxic frame 15
    {3U, 2326U, 1614U, 128U, 128U}, // TextureId::EnemyBeetleToxic frame 16
    {3U, 2062U, 1746U, 128U, 128U}, // TextureId::EnemyBeetleToxic frame 17
    {3U, 2194U, 1746U, 128U, 128U}, // TextureId::EnemyBeetleToxic frame 18
    {3U, 2326U, 1746U, 128U, 128U}, // TextureId::EnemyBeetleToxic frame 19
    {3U, 2U, 2258U, 128U, 128U}, // TextureId::EnemyElementalNeutral frame 0
    {3U, 134U, 2258U, 128U, 128U}, // TextureId::EnemyElementalNeutral frame 1
    {3U, 266U, 2258U, 128U, 128U}, // TextureId::EnemyElementalNeutral frame 2
    {3U, 1442U, 2130U, 128U, 128U}, // TextureId::EnemyElementalNeutral frame 3
    {3U, 1574U, 2130U, 128U, 128U}, // TextureId::EnemyElementalNeutral frame 4
    {3U, 1706U, 2130U, 128U, 128U}, // TextureId::EnemyElementalNeutral frame 5
    {3U, 1838U, 2130U, 128U, 128U}, // TextureId::EnemyElementalNeutral frame 6
    {3U, 794U, 2206U, 128U, 128U}, // TextureId::EnemyElementalNeutral frame 7
    {3U, 398U, 2270U, 128U, 128U}, // TextureId::EnemyElementalNeutral frame 8
    {3U, 530U, 2270U, 128U, 128U}, // TextureId::EnemyElementalNeutral frame 9
    {3U, 662U, 2270U, 128U, 128U}, // TextureId::EnemyElementalNeutral frame 10
    {3U, 2U, 2390U, 128U, 128U}, // TextureId::EnemyElementalNeutral frame 11
    {3U, 134U, 2390U, 128U, 128U}, // TextureId::EnemyElementalNeutral frame 12
    {3U, 266U, 2390U, 128U, 128U}, // TextureId::EnemyElementalNeutral frame 13
    {3U, 926U, 2206U, 128U, 128U}, // TextureId::EnemyElementalNeutral frame 14
    {3U, 1058U, 2206U, 128U, 128U}, // TextureId::EnemyElementalNeutral frame 15
    {3U, 1190U, 2206U, 128U, 128U}, // TextureId::EnemyElementalNeutral frame 16
    {3U, 2458U, 2066U, 128U, 128U}, // TextureId::EnemyElementalNeutral frame 17
    {3U, 1970U, 2142U, 128U, 128U}, // TextureId::EnemyElementalNeutral frame 18
    {3U, 2102U, 2142U, 128U, 128U}, // TextureId::EnemyElementalNeutral frame 19
    {3U, 1046U, 1810U, 128U, 128U}, // TextureId::EnemyElementalLava frame 0
    {3U, 1178U, 1810U, 128U, 128U}, // TextureId::EnemyElementalLava frame 1
    {3U, 1310U, 1810U, 128U, 128U}, // TextureId::EnemyElementalLava frame 2
    {3U, 914U, 1942U, 128U, 128U}, // TextureId::EnemyElementalLava frame 3
    {3U, 518U, 2006U, 128U, 128U}, // TextureId::EnemyElementalLava frame 4
    {3U, 650U, 2006U, 128U, 128U}, // TextureId::EnemyElementalLava frame 5
    {3U, 782U, 2006U, 128U, 128U}, // TextureId::EnemyElementalLava frame 6
    {3U, 1046U, 1942U, 128U, 128U}, // TextureId::EnemyElementalLava frame 7
    {3U, 1178U, 1942U, 128U, 128U}, // TextureId::EnemyElementalLava frame 8
    {3U, 1310U, 1942U, 128U, 128U}, // TextureId::EnemyElementalLava frame 9
    {3U, 2U, 2126U, 128U, 128U}, // TextureId::EnemyElementalLava frame 10
    {3U, 134U, 2126U, 128U, 128U}, // TextureId::EnemyElementalLava frame 11
    {3U, 266U, 2126U, 128U, 128U}, // TextureId::EnemyElementalLava frame 12
    {3U, 914U, 2074U, 128U, 128U}, // TextureId::EnemyElementalLava frame 13
    {3U, 1046U, 2074U, 128U, 128U}, // TextureId::EnemyElementalLava frame 14
    {3U, 1178U, 2074U, 128U, 128U}, // TextureId::EnemyElementalLava frame 15
    {3U, 1310U, 2074U, 128U, 128U}, // TextureId::EnemyElementalLava frame 16
    {3U, 398U, 2138U, 128U, 128U}, // TextureId::EnemyElementalLava frame 17
    {3U, 530U, 2138U, 128U, 128U}, // TextureId::EnemyElementalLava frame 18
    {3U, 662U, 2138U, 128U, 128U}, // TextureId::EnemyElementalLava frame 19
    {3U, 2062U, 1878U, 128U, 128U}, // TextureId::EnemyElementalIce frame 0
    {3U, 2194U, 1878U, 128U, 128U}, // TextureId::EnemyElementalIce frame 1
    {3U, 2326U, 1878U, 128U, 128U}, // TextureId::EnemyElementalIce frame 2
    {3U, 2062U, 2010U, 128U, 128U}, // TextureId::EnemyElementalIce frame 3
    {3U, 2194U, 2010U, 128U, 128U}, // TextureId::EnemyElementalIce frame 4
    {3U, 2326U, 2010U, 128U, 128U}, // TextureId::EnemyElementalIce frame 5
    {3U, 518U, 1610U, 128U, 128U}, // TextureId::EnemyElementalIce frame 6
    {3U, 650U, 1610U, 128U, 128U}, // TextureId::EnemyElementalIce frame 7
    {3U, 782U, 1610U, 128U, 128U}, // TextureId::EnemyElementalIce frame 8
    {3U, 914U, 1678U, 128U, 128U}, // TextureId::EnemyElementalIce frame 9
    {3U, 518U, 1742U, 128U, 128U}, // TextureId::EnemyElementalIce frame 10
    {3U, 650U, 1742U, 128U, 128U}, // TextureId::EnemyElementalIce frame 11
    {3U, 782U, 1742U, 128U, 128U}, // TextureId::EnemyElementalIce frame 12
    {3U, 1046U, 1678U, 128U, 128U}, // TextureId::EnemyElementalIce frame 13
    {3U, 1178U, 1678U, 128U, 128U}, // TextureId::EnemyElementalIce frame 14
    {3U, 1310U, 1678U, 128U, 128U}, // TextureId::EnemyElementalIce frame 15
    {3U, 914U, 1810U, 128U, 128U}, // TextureId::EnemyElementalIce frame 16
    {3U, 518U, 1874U, 128U, 128U}, // TextureId::EnemyElementalIce frame 17
    {3U, 650U, 1874U, 128U, 128U}, // TextureId::EnemyElementalIce frame 18
    {3U, 782U, 1874U, 128U, 128U}, // TextureId::EnemyElementalIce frame 19
    {3U, 2234U, 2142U, 128U, 128U}, // TextureId::EnemyElementalRadioactive frame 0
    {3U, 1322U, 2262U, 128U, 128U}, // TextureId::EnemyElementalRadioactive frame 1
    {3U, 1454U, 2262U, 128U, 128U}, // TextureId::EnemyElementalRadioactive frame 2
    {3U, 1586U, 2262U, 128U, 128U}, // TextureId::EnemyElementalRadioactive frame 3
    {3U, 1718U, 2262U, 128U, 128U}, // TextureId::EnemyElementalRadioactive frame 4
    {3U, 794U, 2338U, 128U, 128U}, // TextureId::EnemyElementalRadioactive frame 5
    {3U, 398U, 2402U, 128U, 128U}, // TextureId::EnemyElementalRadioactive frame 6
    {3U, 530U, 2402U, 128U, 128U}, // TextureId::EnemyElementalRadioactive frame 7
    {3U, 662U, 2402U, 128U, 128U}, // TextureId::EnemyElementalRadioactive frame 8
    {3U, 2U, 2522U, 128U, 128U}, // TextureId::EnemyElementalRadioactive frame 9
    {3U, 134U, 2522U, 128U, 128U}, // TextureId::EnemyElementalRadioactive frame 10
    {3U, 266U, 2522U, 128U, 128U}, // TextureId::EnemyElementalRadioactive frame 11
    {3U, 926U, 2338U, 128U, 128U}, // TextureId::EnemyElementalRadioactive frame 12
    {3U, 1058U, 2338U, 128U, 128U}, // TextureId::EnemyElementalRadioactive frame 13
    {3U, 1190U, 2338U, 128U, 128U}, // TextureId::EnemyElementalRadioactive frame 14
    {3U, 2590U, 2066U, 128U, 128U}, // TextureId::EnemyElementalRadioactive frame 15
    {3U, 2722U, 2066U, 128U, 128U}, // TextureId::EnemyElementalRadioactive frame 16
    {3U, 2854U, 2066U, 128U, 128U}, // TextureId::EnemyElementalRadioactive frame 17
    {3U, 2986U, 2066U, 128U, 128U}, // TextureId::EnemyElementalRadioactive frame 18
    {3U, 3118U, 2066U, 128U, 128U}, // TextureId::EnemyElementalRadioactive frame 19
    {3U, 3250U, 2066U, 128U, 128U}, // TextureId::EnemyElementalToxic frame 0
    {3U, 3382U, 2066U, 128U, 128U}, // TextureId::EnemyElementalToxic frame 1
    {3U, 3514U, 2114U, 128U, 128U}, // TextureId::EnemyElementalToxic frame 2
    {3U, 3646U, 2114U, 128U, 128U}, // TextureId::EnemyElementalToxic frame 3
    {3U, 2U, 2654U, 128U, 128U}, // TextureId::EnemyElementalToxic frame 4
    {3U, 2U, 2786U, 128U, 128U}, // TextureId::EnemyElementalToxic frame 5
    {3U, 2U, 2918U, 128U, 128U}, // TextureId::EnemyElementalToxic frame 6
    {3U, 2U, 3050U, 128U, 128U}, // TextureId::EnemyElementalToxic frame 7
    {3U, 2U, 3182U, 128U, 128U}, // TextureId::EnemyElementalToxic frame 8
    {3U, 2U, 3314U, 128U, 128U}, // TextureId::EnemyElementalToxic frame 9
    {3U, 2U, 3446U, 128U, 128U}, // TextureId::EnemyElementalToxic frame 10
    {3U, 2U, 3578U, 128U, 128U}, // TextureId::EnemyElementalToxic frame 11
    {3U, 134U, 2654U, 128U, 128U}, // TextureId::EnemyElementalToxic frame 12
    {3U, 134U, 2786U, 128U, 128U}, // TextureId::EnemyElementalToxic frame 13
    {3U, 134U, 2918U, 128U, 128U}, // TextureId::EnemyElementalToxic frame 14
    {3U, 134U, 3050U, 128U, 128U}, // TextureId::EnemyElementalToxic frame 15
    {3U, 134U, 3182U, 128U, 128U}, // TextureId::EnemyElementalToxic frame 16
    {3U, 134U, 3314U, 128U, 128U}, // TextureId::EnemyElementalToxic frame 17
    {3U, 134U, 3446U, 128U, 128U}, // TextureId::EnemyElementalToxic frame 18
    {3U, 134U, 3578U, 128U, 128U}, // TextureId::EnemyElementalToxic frame 19
    {3U, 1586U, 3054U, 128U, 128U}, // TextureId::EnemyMammalNeutral frame 0
    {3U, 1586U, 3186U, 128U, 128U}, // TextureId::EnemyMammalNeutral frame 1
    {3U, 1586U, 3318U, 128U, 128U}, // TextureId::EnemyMammalNeutral frame 2
    {3U, 1586U, 3450U, 128U, 128U}, // TextureId::EnemyMammalNeutral frame 3
    {3U, 1586U, 3582U, 128U, 128U}, // TextureId::EnemyMammalNeutral frame 4
    {3U, 1718U, 2790U, 128U, 128U}, // TextureId::EnemyMammalNeutral frame 5
    {3U, 1718U, 2922U, 128U, 128U}, // TextureId::EnemyMammalNeutral frame 6
    {3U, 1718U, 3054U, 128U, 128U}, // TextureId::EnemyMammalNeutral frame 7
    {3U, 1718U, 3186U, 128U, 128U}, // TextureId::EnemyMammalNeutral frame 8
    {3U, 1718U, 3318U, 128U, 128U}, // TextureId::EnemyMammalNeutral frame 9
    {3U, 1718U, 3450U, 128U, 128U}, // TextureId::EnemyMammalNeutral frame 10
    {3U, 1718U, 3582U, 128U, 128U}, // TextureId::EnemyMammalNeutral frame 11
    {3U, 2246U, 2594U, 128U, 128U}, // TextureId::EnemyMammalNeutral frame 12
    {3U, 1850U, 2670U, 128U, 128U}, // TextureId::EnemyMammalNeutral frame 13
    {3U, 1982U, 2670U, 128U, 128U}, // TextureId::EnemyMammalNeutral frame 14
    {3U, 2114U, 2670U, 128U, 128U}, // TextureId::EnemyMammalNeutral frame 15
    {3U, 2378U, 2594U, 128U, 128U}, // TextureId::EnemyMammalNeutral frame 16
    {3U, 2510U, 2594U, 128U, 128U}, // TextureId::EnemyMammalNeutral frame 17
    {3U, 2642U, 2594U, 128U, 128U}, // TextureId::EnemyMammalNeutral frame 18
    {3U, 2774U, 2594U, 128U, 128U}, // TextureId::EnemyMammalNeutral frame 19
    {3U, 3170U, 2462U, 128U, 128U}, // TextureId::EnemyMammalLava frame 0
    {3U, 3302U, 2510U, 128U, 128U}, // TextureId::EnemyMammalLava frame 1
    {3U, 3434U, 2510U, 128U, 128U}, // TextureId::EnemyMammalLava frame 2
    {3U, 3566U, 2510U, 128U, 128U}, // TextureId::EnemyMammalLava frame 3
    {3U, 1322U, 2790U, 128U, 128U}, // TextureId::EnemyMammalLava frame 4
    {3U, 1322U, 2922U, 128U, 128U}, // TextureId::EnemyMammalLava frame 5
    {3U, 1322U, 3054U, 128U, 128U}, // TextureId::EnemyMammalLava frame 6
    {3U, 1322U, 3186U, 128U, 128U}, // TextureId::EnemyMammalLava frame 7
    {3U, 1322U, 3318U, 128U, 128U}, // TextureId::EnemyMammalLava frame 8
    {3U, 1322U, 3450U, 128U, 128U}, // TextureId::EnemyMammalLava frame 9
    {3U, 1322U, 3582U, 128U, 128U}, // TextureId::EnemyMammalLava frame 10
    {3U, 1454U, 2790U, 128U, 128U}, // TextureId::EnemyMammalLava frame 11
    {3U, 1454U, 2922U, 128U, 128U}, // TextureId::EnemyMammalLava frame 12
    {3U, 1454U, 3054U, 128U, 128U}, // TextureId::EnemyMammalLava frame 13
    {3U, 1454U, 3186U, 128U, 128U}, // TextureId::EnemyMammalLava frame 14
    {3U, 1454U, 3318U, 128U, 128U}, // TextureId::EnemyMammalLava frame 15
    {3U, 1454U, 3450U, 128U, 128U}, // TextureId::EnemyMammalLava frame 16
    {3U, 1454U, 3582U, 128U, 128U}, // TextureId::EnemyMammalLava frame 17
    {3U, 1586U, 2790U, 128U, 128U}, // TextureId::EnemyMammalLava frame 18
    {3U, 1586U, 2922U, 128U, 128U}, // TextureId::EnemyMammalLava frame 19
    {3U, 1190U, 2866U, 128U, 128U}, // TextureId::EnemyMammalIce frame 0
    {3U, 1190U, 2998U, 128U, 128U}, // TextureId::EnemyMammalIce frame 1
    {3U, 1190U, 3130U, 128U, 128U}, // TextureId::EnemyMammalIce frame 2
    {3U, 1190U, 3262U, 128U, 128U}, // TextureId::EnemyMammalIce frame 3
    {3U, 1190U, 3394U, 128U, 128U}, // TextureId::EnemyMammalIce frame 4
    {3U, 1190U, 3526U, 128U, 128U}, // TextureId::EnemyMammalIce frame 5
    {3U, 2246U, 2462U, 128U, 128U}, // TextureId::EnemyMammalIce frame 6
    {3U, 1850U, 2538U, 128U, 128U}, // TextureId::EnemyMammalIce frame 7
    {3U, 1982U, 2538U, 128U, 128U}, // TextureId::EnemyMammalIce frame 8
    {3U, 2114U, 2538U, 128U, 128U}, // TextureId::EnemyMammalIce frame 9
    {3U, 1322U, 2658U, 128U, 128U}, // TextureId::EnemyMammalIce frame 10
    {3U, 1454U, 2658U, 128U, 128U}, // TextureId::EnemyMammalIce frame 11
    {3U, 1586U, 2658U, 128U, 128U}, // TextureId::EnemyMammalIce frame 12
    {3U, 1718U, 2658U, 128U, 128U}, // TextureId::EnemyMammalIce frame 13
    {3U, 2378U, 2462U, 128U, 128U}, // TextureId::EnemyMammalIce frame 14
    {3U, 2510U, 2462U, 128U, 128U}, // TextureId::EnemyMammalIce frame 15
    {3U, 2642U, 2462U, 128U, 128U}, // TextureId::EnemyMammalIce frame 16
    {3U, 2774U, 2462U, 128U, 128U}, // TextureId::EnemyMammalIce frame 17
    {3U, 2906U, 2462U, 128U, 128U}, // TextureId::EnemyMammalIce frame 18
    {3U, 3038U, 2462U, 128U, 128U}, // TextureId::EnemyMammalIce frame 19
    {3U, 2906U, 2594U, 128U, 128U}, // TextureId::EnemyMammalRadioactive frame 0
    {3U, 3038U, 2594U, 128U, 128U}, // TextureId::EnemyMammalRadioactive frame 1
    {3U, 3170U, 2594U, 128U, 128U}, // TextureId::EnemyMammalRadioactive frame 2
    {3U, 3302U, 2642U, 128U, 128U}, // TextureId::EnemyMammalRadioactive frame 3
    {3U, 3434U, 2642U, 128U, 128U}, // TextureId::EnemyMammalRadioactive frame 4
    {3U, 3566U, 2642U, 128U, 128U}, // TextureId::EnemyMammalRadioactive frame 5
    {3U, 1850U, 2802U, 128U, 128U}, // TextureId::EnemyMammalRadioactive frame 6
    {3U, 1850U, 2934U, 128U, 128U}, // TextureId::EnemyMammalRadioactive frame 7
    {3U, 1850U, 3066U, 128U, 128U}, // TextureId::EnemyMammalRadioactive frame 8
    {3U, 1850U, 3198U, 128U, 128U}, // TextureId::EnemyMammalRadioactive frame 9
    {3U, 1850U, 3330U, 128U, 128U}, // TextureId::EnemyMammalRadioactive frame 10
    {3U, 1850U, 3462U, 128U, 128U}, // TextureId::EnemyMammalRadioactive frame 11
    {3U, 1850U, 3594U, 128U, 128U}, // TextureId::EnemyMammalRadioactive frame 12
    {3U, 1982U, 2802U, 128U, 128U}, // TextureId::EnemyMammalRadioactive frame 13
    {3U, 1982U, 2934U, 128U, 128U}, // TextureId::EnemyMammalRadioactive frame 14
    {3U, 1982U, 3066U, 128U, 128U}, // TextureId::EnemyMammalRadioactive frame 15
    {3U, 1982U, 3198U, 128U, 128U}, // TextureId::EnemyMammalRadioactive frame 16
    {3U, 1982U, 3330U, 128U, 128U}, // TextureId::EnemyMammalRadioactive frame 17
    {3U, 1982U, 3462U, 128U, 128U}, // TextureId::EnemyMammalRadioactive frame 18
    {3U, 1982U, 3594U, 128U, 128U}, // TextureId::EnemyMammalRadioactive frame 19
    {3U, 2114U, 2802U, 128U, 128U}, // TextureId::EnemyMammalToxic frame 0
    {3U, 2114U, 2934U, 128U, 128U}, // TextureId::EnemyMammalToxic frame 1
    {3U, 2114U, 3066U, 128U, 128U}, // TextureId::EnemyMammalToxic frame 2
    {3U, 2114U, 3198U, 128U, 128U}, // TextureId::EnemyMammalToxic frame 3
    {3U, 2114U, 3330U, 128U, 128U}, // TextureId::EnemyMammalToxic frame 4
    {3U, 2114U, 3462U, 128U, 128U}, // TextureId::EnemyMammalToxic frame 5
    {3U, 2114U, 3594U, 128U, 128U}, // TextureId::EnemyMammalToxic frame 6
    {3U, 2246U, 2774U, 128U, 128U}, // TextureId::EnemyMammalToxic frame 7
    {3U, 2246U, 2906U, 128U, 128U}, // TextureId::EnemyMammalToxic frame 8
    {3U, 2246U, 3038U, 128U, 128U}, // TextureId::EnemyMammalToxic frame 9
    {3U, 2246U, 3170U, 128U, 128U}, // TextureId::EnemyMammalToxic frame 10
    {3U, 2246U, 3302U, 128U, 128U}, // TextureId::EnemyMammalToxic frame 11
    {3U, 2246U, 3434U, 128U, 128U}, // TextureId::EnemyMammalToxic frame 12
    {3U, 2246U, 3566U, 128U, 128U}, // TextureId::EnemyMammalToxic frame 13
    {3U, 2378U, 2726U, 128U, 128U}, // TextureId::EnemyMammalToxic frame 14
    {3U, 2510U, 2726U, 128U, 128U}, // TextureId::EnemyMammalToxic frame 15
    {3U, 2642U, 2726U, 128U, 128U}, // TextureId::EnemyMammalToxic frame 16
    {3U, 2774U, 2726U, 128U, 128U}, // TextureId::EnemyMammalToxic frame 17
    {3U, 2906U, 2726U, 128U, 128U}, // TextureId::EnemyMammalToxic frame 18
    {3U, 3038U, 2726U, 128U, 128U}, // TextureId::EnemyMammalToxic frame 19
    {3U, 3434U, 3434U, 128U, 128U}, // TextureId::EnemySpawnerNeutral frame 0
    {3U, 3566U, 3434U, 128U, 128U}, // TextureId::EnemySpawnerNeutral frame 1
    {3U, 3434U, 3566U, 128U, 128U}, // TextureId::EnemySpawnerNeutral frame 2
    {3U, 3566U, 3566U, 128U, 128U}, // TextureId::EnemySpawnerNeutral frame 3
    {4U, 2U, 2U, 128U, 128U}, // TextureId::EnemySpawnerNeutral frame 4
    {4U, 134U, 2U, 128U, 128U}, // TextureId::EnemySpawnerNeutral frame 5
    {4U, 266U, 2U, 128U, 128U}, // TextureId::EnemySpawnerNeutral frame 6
    {4U, 398U, 2U, 128U, 128U}, // TextureId::EnemySpawnerNeutral frame 7
    {4U, 530U, 2U, 128U, 128U}, // TextureId::EnemySpawnerNeutral frame 8
    {4U, 662U, 2U, 128U, 128U}, // TextureId::EnemySpawnerNeutral frame 9
    {4U, 794U, 2U, 128U, 128U}, // TextureId::EnemySpawnerNeutral frame 10
    {4U, 926U, 2U, 128U, 128U}, // TextureId::EnemySpawnerNeutral frame 11
    {4U, 1058U, 2U, 128U, 128U}, // TextureId::EnemySpawnerNeutral frame 12
    {4U, 1190U, 2U, 128U, 128U}, // TextureId::EnemySpawnerNeutral frame 13
    {4U, 1322U, 2U, 128U, 128U}, // TextureId::EnemySpawnerNeutral frame 14
    {4U, 1454U, 2U, 128U, 128U}, // TextureId::EnemySpawnerNeutral frame 15
    {4U, 1586U, 2U, 128U, 128U}, // TextureId::EnemySpawnerNeutral frame 16
    {4U, 1718U, 2U, 128U, 128U}, // TextureId::EnemySpawnerNeutral frame 17
    {4U, 1850U, 2U, 128U, 128U}, // TextureId::EnemySpawnerNeutral frame 18
    {4U, 1982U, 2U, 128U, 128U}, // TextureId::EnemySpawnerNeutral frame 19
    {3U, 3302U, 3170U, 128U, 128U}, // TextureId::EnemySpawnerLava frame 0
    {3U, 3434U, 3170U, 128U, 128U}, // TextureId::EnemySpawnerLava frame 1
    {3U, 3566U, 3170U, 128U, 128U}, // TextureId::EnemySpawnerLava frame 2
    {3U, 2774U, 3302U, 128U, 128U}, // TextureId::EnemySpawnerLava frame 3
    {3U, 2774U, 3434U, 128U, 128U}, // TextureId::EnemySpawnerLava frame 4
    {3U, 2774U, 3566U, 128U, 128U}, // TextureId::EnemySpawnerLava frame 5
    {3U, 2906U, 3254U, 128U, 128U}, // TextureId::EnemySpawnerLava frame 6
    {3U, 3038U, 3254U, 128U, 128U}, // TextureId::EnemySpawnerLava frame 7
    {3U, 3170U, 3254U, 128U, 128U}, // TextureId::EnemySpawnerLava frame 8
    {3U, 2906U, 3386U, 128U, 128U}, // TextureId::EnemySpawnerLava frame 9
    {3U, 2906U, 3518U, 128U, 128U}, // TextureId::EnemySpawnerLava frame 10
    {3U, 3038U, 3386U, 128U, 128U}, // TextureId::EnemySpawnerLava frame 11
    {3U, 3038U, 3518U, 128U, 128U}, // TextureId::EnemySpawnerLava frame 12
    {3U, 3170U, 3386U, 128U, 128U}, // TextureId::EnemySpawnerLava frame 13
    {3U, 3170U, 3518U, 128U, 128U}, // TextureId::EnemySpawnerLava frame 14
    {3U, 3302U, 3302U, 128U, 128U}, // TextureId::EnemySpawnerLava frame 15
    {3U, 3434U, 3302U, 128U, 128U}, // TextureId::EnemySpawnerLava frame 16
    {3U, 3566U, 3302U, 128U, 128U}, // TextureId::EnemySpawnerLava frame 17
    {3U, 3302U, 3434U, 128U, 128U}, // TextureId::EnemySpawnerLava frame 18
    {3U, 3302U, 3566U, 128U, 128U}, // TextureId::EnemySpawnerLava frame 19
    {3U, 2510U, 3170U, 128U, 128U}, // TextureId::EnemySpawnerIce frame 0
    {3U, 2510U, 3302U, 128U, 128U}, // TextureId::EnemySpawnerIce frame 1
    {3U, 2510U, 3434U, 128U, 128U}, // TextureId::EnemySpawnerIce frame 2
    {3U, 2510U, 3566U, 128U, 128U}, // TextureId::EnemySpawnerIce frame 3
    {3U, 2642U, 2990U, 128U, 128U}, // TextureId::EnemySpawnerIce frame 4
    {3U, 2774U, 2990U, 128U, 128U}, // TextureId::EnemySpawnerIce frame 5
    {3U, 2906U, 2990U, 128U, 128U}, // TextureId::EnemySpawnerIce frame 6
    {3U, 3038U, 2990U, 128U, 128U}, // TextureId::EnemySpawnerIce frame 7
    {3U, 3170U, 2990U, 128U, 128U}, // TextureId::EnemySpawnerIce frame 8
    {3U, 3302U, 3038U, 128U, 128U}, // TextureId::EnemySpawnerIce frame 9
    {3U, 3434U, 3038U, 128U, 128U}, // TextureId::EnemySpawnerIce frame 10
    {3U, 3566U, 3038U, 128U, 128U}, // TextureId::EnemySpawnerIce frame 11
    {3U, 2642U, 3170U, 128U, 128U}, // TextureId::EnemySpawnerIce frame 12
    {3U, 2642U, 3302U, 128U, 128U}, // TextureId::EnemySpawnerIce frame 13
    {3U, 2642U, 3434U, 128U, 128U}, // TextureId::EnemySpawnerIce frame 14
    {3U, 2642U, 3566U, 128U, 128U}, // TextureId::EnemySpawnerIce frame 15
    {3U, 2774U, 3122U, 128U, 128U}, // TextureId::EnemySpawnerIce frame 16
    {3U, 2906U, 3122U, 128U, 128U}, // TextureId::EnemySpawnerIce frame 17
    {3U, 3038U, 3122U, 128U, 128U}, // TextureId::EnemySpawnerIce frame 18
    {3U, 3170U, 3122U, 128U, 128U}, // TextureId::EnemySpawnerIce frame 19
    {4U, 2114U, 2U, 128U, 128U}, // TextureId::EnemySpawnerRadioactive frame 0
    {4U, 2246U, 2U, 128U, 128U}, // TextureId::EnemySpawnerRadioactive frame 1
    {4U, 2378U, 2U, 128U, 128U}, // TextureId::EnemySpawnerRadioactive frame 2
    {4U, 2510U, 2U, 128U, 128U}, // TextureId::EnemySpawnerRadioactive frame 3
    {4U, 2642U, 2U, 128U, 128U}, // TextureId::EnemySpawnerRadioactive frame 4
    {4U, 2774U, 2U, 128U, 128U}, // TextureId::EnemySpawnerRadioactive frame 5
    {4U, 2906U, 2U, 128U, 128U}, // TextureId::EnemySpawnerRadioactive frame 6
    {4U, 3038U, 2U, 128U, 128U}, // TextureId::EnemySpawnerRadioactive frame 7
    {4U, 3170U, 2U, 128U, 128U}, // TextureId::EnemySpawnerRadioactive frame 8
    {4U, 3302U, 2U, 128U, 128U}, // TextureId::EnemySpawnerRadioactive frame 9
    {4U, 3434U, 2U, 128U, 128U}, // TextureId::EnemySpawnerRadioactive frame 10
    {4U, 3566U, 2U, 128U, 128U}, // TextureId::EnemySpawnerRadioactive frame 11
    {4U, 2U, 134U, 128U, 128U}, // TextureId::EnemySpawnerRadioactive frame 12
    {4U, 2U, 266U, 128U, 128U}, // TextureId::EnemySpawnerRadioactive frame 13
    {4U, 2U, 398U, 128U, 128U}, // TextureId::EnemySpawnerRadioactive frame 14
    {4U, 2U, 530U, 128U, 128U}, // TextureId::EnemySpawnerRadioactive frame 15
    {4U, 2U, 662U, 128U, 128U}, // TextureId::EnemySpawnerRadioactive frame 16
    {4U, 2U, 794U, 128U, 128U}, // TextureId::EnemySpawnerRadioactive frame 17
    {4U, 2U, 926U, 128U, 128U}, // TextureId::EnemySpawnerRadioactive frame 18
    {4U, 2U, 1058U, 128U, 128U}, // TextureId::EnemySpawnerRadioactive frame 19
    {4U, 2U, 1190U, 128U, 128U}, // TextureId::EnemySpawnerToxic frame 0
    {4U, 2U, 1322U, 128U, 128U}, // TextureId::EnemySpawnerToxic frame 1
    {4U, 2U, 1454U, 128U, 128U}, // TextureId::EnemySpawnerToxic frame 2
    {4U, 2U, 1586U, 128U, 128U}, // TextureId::EnemySpawnerToxic frame 3
    {4U, 2U, 1718U, 128U, 128U}, // TextureId::EnemySpawnerToxic frame 4
    {4U, 2U, 1850U, 128U, 128U}, // TextureId::EnemySpawnerToxic frame 5
    {4U, 2U, 1982U, 128U, 128U}, // TextureId::EnemySpawnerToxic frame 6
    {4U, 2U, 2114U, 128U, 128U}, // TextureId::EnemySpawnerToxic frame 7
    {4U, 2U, 2246U, 128U, 128U}, // TextureId::EnemySpawnerToxic frame 8
    {4U, 2U, 2378U, 128U, 128U}, // TextureId::EnemySpawnerToxic frame 9
    {4U, 2U, 2510U, 128U, 128U}, // TextureId::EnemySpawnerToxic frame 10
    {4U, 2U, 2642U, 128U, 128U}, // TextureId::EnemySpawnerToxic frame 11
    {4U, 2U, 2774U, 128U, 128U}, // TextureId::EnemySpawnerToxic frame 12
    {4U, 2U, 2906U, 128U, 128U}, // TextureId::EnemySpawnerToxic frame 13
    {4U, 2U, 3038U, 128U, 128U}, // TextureId::EnemySpawnerToxic frame 14
    {4U, 2U, 3170U, 128U, 128U}, // TextureId::EnemySpawnerToxic frame 15
    {4U, 2U, 3302U, 128U, 128U}, // TextureId::EnemySpawnerToxic frame 16
    {4U, 2U, 3434U, 128U, 128U}, // TextureId::EnemySpawnerToxic frame 17
    {4U, 2U, 3566U, 128U, 128U}, // TextureId::EnemySpawnerToxic frame 18
    {4U, 134U, 134U, 128U, 128U}, // TextureId::EnemySpawnerToxic frame 19
    {0U, 1222U, 3082U, 256U, 256U}, // TextureId::MiningArtifact frame 0
    {0U, 2U, 3286U, 1216U, 64U}, // TextureId::MiningTilesMoon frame 0
    {0U, 2U, 3218U, 1216U, 64U}, // TextureId::MiningTilesMars frame 0
    {0U, 2U, 3082U, 1216U, 64U}, // TextureId::MiningTilesIo frame 0
    {0U, 2U, 3490U, 1216U, 64U}, // TextureId::MiningTilesSaturn frame 0
    {0U, 2U, 3558U, 1216U, 64U}, // TextureId::MiningTilesUranus frame 0
    {0U, 2U, 3354U, 1216U, 64U}, // TextureId::MiningTilesNeptune frame 0
    {0U, 2U, 3150U, 1216U, 64U}, // TextureId::MiningTilesKhepriPrime frame 0
    {0U, 2U, 3422U, 1216U, 64U}, // TextureId::MiningTilesRiftBelt frame 0
    {0U, 2U, 2U, 1216U, 2048U}, // TextureId::MiningTilesPostSolarLibrary frame 0
    {1U, 2U, 2U, 1254U, 1254U}, // TextureId::MissionControlFennec frame 0
    {2U, 2518U, 2U, 1254U, 1254U}, // TextureId::ServiceDock frame 0
    {1U, 1260U, 2U, 1254U, 1254U}, // TextureId::MissionControlFennecConcerned frame 0
    {0U, 1542U, 2128U, 1254U, 1254U}, // TextureId::MiningTunnelBackdrop frame 0
    {3U, 3170U, 2726U, 128U, 128U}, // TextureId::EnemySecurityDrone frame 0
    {3U, 3302U, 2774U, 128U, 128U}, // TextureId::EnemySecurityDrone frame 1
    {3U, 3434U, 2774U, 128U, 128U}, // TextureId::EnemySecurityDrone frame 2
    {3U, 3566U, 2774U, 128U, 128U}, // TextureId::EnemySecurityDrone frame 3
    {3U, 2378U, 2906U, 128U, 128U}, // TextureId::EnemySecurityDrone frame 4
    {3U, 2378U, 3038U, 128U, 128U}, // TextureId::EnemySecurityDrone frame 5
    {3U, 2378U, 3170U, 128U, 128U}, // TextureId::EnemySecurityDrone frame 6
    {3U, 2378U, 3302U, 128U, 128U}, // TextureId::EnemySecurityDrone frame 7
    {3U, 2378U, 3434U, 128U, 128U}, // TextureId::EnemySecurityDrone frame 8
    {3U, 2378U, 3566U, 128U, 128U}, // TextureId::EnemySecurityDrone frame 9
    {3U, 2510U, 2858U, 128U, 128U}, // TextureId::EnemySecurityDrone frame 10
    {3U, 2642U, 2858U, 128U, 128U}, // TextureId::EnemySecurityDrone frame 11
    {3U, 2774U, 2858U, 128U, 128U}, // TextureId::EnemySecurityDrone frame 12
    {3U, 2906U, 2858U, 128U, 128U}, // TextureId::EnemySecurityDrone frame 13
    {3U, 3038U, 2858U, 128U, 128U}, // TextureId::EnemySecurityDrone frame 14
    {3U, 3170U, 2858U, 128U, 128U}, // TextureId::EnemySecurityDrone frame 15
    {3U, 3302U, 2906U, 128U, 128U}, // TextureId::EnemySecurityDrone frame 16
    {3U, 3434U, 2906U, 128U, 128U}, // TextureId::EnemySecurityDrone frame 17
    {3U, 3566U, 2906U, 128U, 128U}, // TextureId::EnemySecurityDrone frame 18
    {3U, 2510U, 3038U, 128U, 128U}, // TextureId::EnemySecurityDrone frame 19
    {2U, 1260U, 1260U, 1254U, 1254U}, // TextureId::StraylightDock frame 0
    {2U, 2518U, 1260U, 1254U, 1254U}, // TextureId::Sun frame 0
    {0U, 1222U, 3342U, 256U, 256U}, // TextureId::MiningRigFuelCell frame 0
    {0U, 2U, 2054U, 1536U, 1024U}, // TextureId::StraylightDockHull frame 0
}};

inline constexpr std::array<SceneAtlasTexture, 88U>
    kSceneAtlasTextures {{
    {}, // TextureId::None
    {512U, 512U, 512U, 512U, 0U, 1U, 1U, 1U}, // TextureId::Earth
    {512U, 512U, 512U, 512U, 1U, 1U, 1U, 1U}, // TextureId::Moon
    {512U, 512U, 512U, 512U, 2U, 1U, 1U, 1U}, // TextureId::Mars
    {1024U, 1024U, 1024U, 1024U, 3U, 1U, 1U, 1U}, // TextureId::RocketClosed
    {1024U, 128U, 128U, 128U, 4U, 8U, 1U, 8U}, // TextureId::Explosion
    {768U, 128U, 128U, 128U, 12U, 6U, 1U, 6U}, // TextureId::Thrust
    {512U, 512U, 512U, 512U, 18U, 1U, 1U, 1U}, // TextureId::MiningDrone
    {672U, 112U, 112U, 112U, 19U, 6U, 1U, 6U}, // TextureId::DrillBit
    {4096U, 576U, 1024U, 576U, 25U, 4U, 1U, 4U}, // TextureId::LocalSolarBackground
    {512U, 512U, 512U, 512U, 29U, 1U, 1U, 1U}, // TextureId::Mercury
    {512U, 512U, 512U, 512U, 30U, 1U, 1U, 1U}, // TextureId::Venus
    {512U, 512U, 512U, 512U, 31U, 1U, 1U, 1U}, // TextureId::Jupiter
    {512U, 512U, 512U, 512U, 32U, 1U, 1U, 1U}, // TextureId::Saturn
    {512U, 512U, 512U, 512U, 33U, 1U, 1U, 1U}, // TextureId::Uranus
    {512U, 512U, 512U, 512U, 34U, 1U, 1U, 1U}, // TextureId::Neptune
    {1254U, 1254U, 1254U, 1254U, 35U, 1U, 1U, 1U}, // TextureId::ArkOperational
    {1254U, 1254U, 1254U, 1254U, 36U, 1U, 1U, 1U}, // TextureId::ArkDamaged
    {1254U, 1254U, 1254U, 1254U, 37U, 1U, 1U, 1U}, // TextureId::OuterPlanet01
    {1254U, 1254U, 1254U, 1254U, 38U, 1U, 1U, 1U}, // TextureId::OuterPlanet02
    {1254U, 1254U, 1254U, 1254U, 39U, 1U, 1U, 1U}, // TextureId::OuterPlanet03
    {1254U, 1254U, 1254U, 1254U, 40U, 1U, 1U, 1U}, // TextureId::OuterPlanet04
    {1254U, 1254U, 1254U, 1254U, 41U, 1U, 1U, 1U}, // TextureId::OuterPlanet05
    {1254U, 1254U, 1254U, 1254U, 42U, 1U, 1U, 1U}, // TextureId::OuterPlanet06
    {1254U, 1254U, 1254U, 1254U, 43U, 1U, 1U, 1U}, // TextureId::OuterPlanet07
    {1254U, 1254U, 1254U, 1254U, 44U, 1U, 1U, 1U}, // TextureId::OuterPlanet08
    {1254U, 1254U, 1254U, 1254U, 45U, 1U, 1U, 1U}, // TextureId::OuterPlanet09
    {1024U, 1024U, 1024U, 1024U, 46U, 1U, 1U, 1U}, // TextureId::RocketOpen
    {512U, 512U, 512U, 512U, 47U, 1U, 1U, 1U}, // TextureId::MiniDroneMining
    {512U, 512U, 512U, 512U, 48U, 1U, 1U, 1U}, // TextureId::MiniDroneResource
    {512U, 512U, 512U, 512U, 49U, 1U, 1U, 1U}, // TextureId::MiniDroneSurvey
    {512U, 512U, 512U, 512U, 50U, 1U, 1U, 1U}, // TextureId::MiniDroneHazard
    {512U, 512U, 512U, 512U, 51U, 1U, 1U, 1U}, // TextureId::MiniDroneAttack
    {512U, 512U, 512U, 512U, 52U, 1U, 1U, 1U}, // TextureId::MiniDroneDefense
    {1024U, 1024U, 1024U, 1024U, 53U, 1U, 1U, 1U}, // TextureId::HeroicCapybara
    {1254U, 1254U, 1254U, 1254U, 54U, 1U, 1U, 1U}, // TextureId::JetpackCapybara
    {512U, 512U, 512U, 512U, 55U, 1U, 1U, 1U}, // TextureId::PoiGuidanceArrow
    {512U, 512U, 512U, 512U, 56U, 1U, 1U, 1U}, // TextureId::Asteroid
    {1821U, 864U, 1821U, 864U, 57U, 1U, 1U, 1U}, // TextureId::FlightInstrumentCluster
    {2560U, 128U, 128U, 128U, 58U, 20U, 1U, 20U}, // TextureId::EnemyAntNeutral
    {2560U, 128U, 128U, 128U, 78U, 20U, 1U, 20U}, // TextureId::EnemyAntLava
    {2560U, 128U, 128U, 128U, 98U, 20U, 1U, 20U}, // TextureId::EnemyAntIce
    {2560U, 128U, 128U, 128U, 118U, 20U, 1U, 20U}, // TextureId::EnemyAntRadioactive
    {2560U, 128U, 128U, 128U, 138U, 20U, 1U, 20U}, // TextureId::EnemyAntToxic
    {2560U, 128U, 128U, 128U, 158U, 20U, 1U, 20U}, // TextureId::EnemyFlyingNeutral
    {2560U, 128U, 128U, 128U, 178U, 20U, 1U, 20U}, // TextureId::EnemyFlyingLava
    {2560U, 128U, 128U, 128U, 198U, 20U, 1U, 20U}, // TextureId::EnemyFlyingIce
    {2560U, 128U, 128U, 128U, 218U, 20U, 1U, 20U}, // TextureId::EnemyFlyingRadioactive
    {2560U, 128U, 128U, 128U, 238U, 20U, 1U, 20U}, // TextureId::EnemyFlyingToxic
    {2560U, 128U, 128U, 128U, 258U, 20U, 1U, 20U}, // TextureId::EnemyBeetleNeutral
    {2560U, 128U, 128U, 128U, 278U, 20U, 1U, 20U}, // TextureId::EnemyBeetleLava
    {2560U, 128U, 128U, 128U, 298U, 20U, 1U, 20U}, // TextureId::EnemyBeetleIce
    {2560U, 128U, 128U, 128U, 318U, 20U, 1U, 20U}, // TextureId::EnemyBeetleRadioactive
    {2560U, 128U, 128U, 128U, 338U, 20U, 1U, 20U}, // TextureId::EnemyBeetleToxic
    {2560U, 128U, 128U, 128U, 358U, 20U, 1U, 20U}, // TextureId::EnemyElementalNeutral
    {2560U, 128U, 128U, 128U, 378U, 20U, 1U, 20U}, // TextureId::EnemyElementalLava
    {2560U, 128U, 128U, 128U, 398U, 20U, 1U, 20U}, // TextureId::EnemyElementalIce
    {2560U, 128U, 128U, 128U, 418U, 20U, 1U, 20U}, // TextureId::EnemyElementalRadioactive
    {2560U, 128U, 128U, 128U, 438U, 20U, 1U, 20U}, // TextureId::EnemyElementalToxic
    {2560U, 128U, 128U, 128U, 458U, 20U, 1U, 20U}, // TextureId::EnemyMammalNeutral
    {2560U, 128U, 128U, 128U, 478U, 20U, 1U, 20U}, // TextureId::EnemyMammalLava
    {2560U, 128U, 128U, 128U, 498U, 20U, 1U, 20U}, // TextureId::EnemyMammalIce
    {2560U, 128U, 128U, 128U, 518U, 20U, 1U, 20U}, // TextureId::EnemyMammalRadioactive
    {2560U, 128U, 128U, 128U, 538U, 20U, 1U, 20U}, // TextureId::EnemyMammalToxic
    {2560U, 128U, 128U, 128U, 558U, 20U, 1U, 20U}, // TextureId::EnemySpawnerNeutral
    {2560U, 128U, 128U, 128U, 578U, 20U, 1U, 20U}, // TextureId::EnemySpawnerLava
    {2560U, 128U, 128U, 128U, 598U, 20U, 1U, 20U}, // TextureId::EnemySpawnerIce
    {2560U, 128U, 128U, 128U, 618U, 20U, 1U, 20U}, // TextureId::EnemySpawnerRadioactive
    {2560U, 128U, 128U, 128U, 638U, 20U, 1U, 20U}, // TextureId::EnemySpawnerToxic
    {256U, 256U, 256U, 256U, 658U, 1U, 1U, 1U}, // TextureId::MiningArtifact
    {1216U, 64U, 1216U, 64U, 659U, 1U, 1U, 1U}, // TextureId::MiningTilesMoon
    {1216U, 64U, 1216U, 64U, 660U, 1U, 1U, 1U}, // TextureId::MiningTilesMars
    {1216U, 64U, 1216U, 64U, 661U, 1U, 1U, 1U}, // TextureId::MiningTilesIo
    {1216U, 64U, 1216U, 64U, 662U, 1U, 1U, 1U}, // TextureId::MiningTilesSaturn
    {1216U, 64U, 1216U, 64U, 663U, 1U, 1U, 1U}, // TextureId::MiningTilesUranus
    {1216U, 64U, 1216U, 64U, 664U, 1U, 1U, 1U}, // TextureId::MiningTilesNeptune
    {1216U, 64U, 1216U, 64U, 665U, 1U, 1U, 1U}, // TextureId::MiningTilesKhepriPrime
    {1216U, 64U, 1216U, 64U, 666U, 1U, 1U, 1U}, // TextureId::MiningTilesRiftBelt
    {1216U, 2048U, 1216U, 2048U, 667U, 1U, 1U, 1U}, // TextureId::MiningTilesPostSolarLibrary
    {1254U, 1254U, 1254U, 1254U, 668U, 1U, 1U, 1U}, // TextureId::MissionControlFennec
    {1254U, 1254U, 1254U, 1254U, 669U, 1U, 1U, 1U}, // TextureId::ServiceDock
    {1254U, 1254U, 1254U, 1254U, 670U, 1U, 1U, 1U}, // TextureId::MissionControlFennecConcerned
    {1254U, 1254U, 1254U, 1254U, 671U, 1U, 1U, 1U}, // TextureId::MiningTunnelBackdrop
    {2560U, 128U, 128U, 128U, 672U, 20U, 1U, 20U}, // TextureId::EnemySecurityDrone
    {1254U, 1254U, 1254U, 1254U, 692U, 1U, 1U, 1U}, // TextureId::StraylightDock
    {1254U, 1254U, 1254U, 1254U, 693U, 1U, 1U, 1U}, // TextureId::Sun
    {256U, 256U, 256U, 256U, 694U, 1U, 1U, 1U}, // TextureId::MiningRigFuelCell
    {1536U, 1024U, 1536U, 1024U, 695U, 1U, 1U, 1U}, // TextureId::StraylightDockHull
}};

static_assert(kSceneAtlasTextures.size() == textureIndex(TextureId::Count));

} // namespace rocket
