// Generated by tools/build-scene-atlas.py. Do not edit by hand.
#pragma once

#include "render/ScenePacket.h"

#include <array>
#include <cstddef>
#include <cstdint>

namespace rocket {

struct SceneAtlasPage {
    const char* key = nullptr;
    const char* relativePath = nullptr;
    std::uint16_t width = 0;
    std::uint16_t height = 0;
};

struct SceneAtlasFrame {
    std::uint8_t page = 0;
    std::uint16_t x = 0;
    std::uint16_t y = 0;
    std::uint16_t width = 0;
    std::uint16_t height = 0;
};

struct SceneAtlasTexture {
    std::uint16_t sourceWidth = 0;
    std::uint16_t sourceHeight = 0;
    std::uint16_t frameWidth = 0;
    std::uint16_t frameHeight = 0;
    std::uint16_t firstFrame = 0;
    std::uint8_t columns = 0;
    std::uint8_t rows = 0;
    std::uint8_t frameCount = 0;
};

inline constexpr std::array<SceneAtlasPage, 3U> kSceneAtlasPages {{
    {"scene_atlas_0", "assets/scene-atlas/scene-atlas-0.png", 3774U, 3774U},
    {"scene_atlas_1", "assets/scene-atlas/scene-atlas-1.png", 3740U, 3664U},
    {"scene_atlas_2", "assets/scene-atlas/scene-atlas-2.png", 1548U, 516U},
}};

inline constexpr std::array<SceneAtlasFrame, 54U>
    kSceneAtlasFrames {{
    {1U, 1030U, 2420U, 512U, 512U}, // TextureId::Earth frame 0
    {1U, 2578U, 3090U, 512U, 512U}, // TextureId::Moon frame 0
    {1U, 1546U, 2420U, 512U, 512U}, // TextureId::Mars frame 0
    {1U, 2518U, 1030U, 1024U, 1024U}, // TextureId::RocketClosed frame 0
    {1U, 3610U, 2U, 128U, 128U}, // TextureId::Explosion frame 0
    {1U, 3610U, 134U, 128U, 128U}, // TextureId::Explosion frame 1
    {1U, 3610U, 266U, 128U, 128U}, // TextureId::Explosion frame 2
    {1U, 3610U, 398U, 128U, 128U}, // TextureId::Explosion frame 3
    {1U, 3610U, 530U, 128U, 128U}, // TextureId::Explosion frame 4
    {1U, 3610U, 662U, 128U, 128U}, // TextureId::Explosion frame 5
    {1U, 3610U, 794U, 128U, 128U}, // TextureId::Explosion frame 6
    {1U, 3610U, 926U, 128U, 128U}, // TextureId::Explosion frame 7
    {1U, 3610U, 1058U, 128U, 128U}, // TextureId::Thrust frame 0
    {1U, 3610U, 1190U, 128U, 128U}, // TextureId::Thrust frame 1
    {1U, 3610U, 1322U, 128U, 128U}, // TextureId::Thrust frame 2
    {1U, 3610U, 1454U, 128U, 128U}, // TextureId::Thrust frame 3
    {1U, 3610U, 1586U, 128U, 128U}, // TextureId::Thrust frame 4
    {1U, 3610U, 1718U, 128U, 128U}, // TextureId::Thrust frame 5
    {1U, 3094U, 2574U, 512U, 512U}, // TextureId::MiningDrone frame 0
    {1U, 3610U, 1850U, 112U, 112U}, // TextureId::DrillBit frame 0
    {1U, 3610U, 1966U, 112U, 112U}, // TextureId::DrillBit frame 1
    {1U, 3610U, 2082U, 112U, 112U}, // TextureId::DrillBit frame 2
    {1U, 3610U, 2198U, 112U, 112U}, // TextureId::DrillBit frame 3
    {1U, 3610U, 2314U, 112U, 112U}, // TextureId::DrillBit frame 4
    {1U, 3610U, 2430U, 112U, 112U}, // TextureId::DrillBit frame 5
    {1U, 2U, 3086U, 1024U, 576U}, // TextureId::LocalSolarBackground frame 0
    {1U, 2U, 1260U, 1024U, 576U}, // TextureId::LocalSolarBackground frame 1
    {1U, 1030U, 1260U, 1024U, 576U}, // TextureId::LocalSolarBackground frame 2
    {1U, 1030U, 1840U, 1024U, 576U}, // TextureId::LocalSolarBackground frame 3
    {1U, 1546U, 2936U, 512U, 512U}, // TextureId::Mercury frame 0
    {2U, 1034U, 2U, 512U, 512U}, // TextureId::Venus frame 0
    {1U, 1030U, 2936U, 512U, 512U}, // TextureId::Jupiter frame 0
    {2U, 2U, 2U, 512U, 512U}, // TextureId::Saturn frame 0
    {2U, 518U, 2U, 512U, 512U}, // TextureId::Uranus frame 0
    {1U, 3094U, 3090U, 512U, 512U}, // TextureId::Neptune frame 0
    {1U, 1260U, 2U, 1254U, 1254U}, // TextureId::ArkOperational frame 0
    {1U, 2U, 2U, 1254U, 1254U}, // TextureId::ArkDamaged frame 0
    {0U, 2U, 2U, 1254U, 1254U}, // TextureId::OuterPlanet01 frame 0
    {0U, 1260U, 2U, 1254U, 1254U}, // TextureId::OuterPlanet02 frame 0
    {0U, 2518U, 2U, 1254U, 1254U}, // TextureId::OuterPlanet03 frame 0
    {0U, 2U, 1260U, 1254U, 1254U}, // TextureId::OuterPlanet04 frame 0
    {0U, 2U, 2518U, 1254U, 1254U}, // TextureId::OuterPlanet05 frame 0
    {0U, 1260U, 1260U, 1254U, 1254U}, // TextureId::OuterPlanet06 frame 0
    {0U, 2518U, 1260U, 1254U, 1254U}, // TextureId::OuterPlanet07 frame 0
    {0U, 1260U, 2518U, 1254U, 1254U}, // TextureId::OuterPlanet08 frame 0
    {0U, 2518U, 2518U, 1254U, 1254U}, // TextureId::OuterPlanet09 frame 0
    {1U, 2U, 2058U, 1024U, 1024U}, // TextureId::RocketOpen frame 0
    {1U, 2062U, 2574U, 512U, 512U}, // TextureId::MiniDroneMining frame 0
    {1U, 2062U, 3090U, 512U, 512U}, // TextureId::MiniDroneResource frame 0
    {1U, 2578U, 2574U, 512U, 512U}, // TextureId::MiniDroneSurvey frame 0
    {1U, 3094U, 2058U, 512U, 512U}, // TextureId::MiniDroneHazard frame 0
    {1U, 2062U, 2058U, 512U, 512U}, // TextureId::MiniDroneAttack frame 0
    {1U, 2578U, 2058U, 512U, 512U}, // TextureId::MiniDroneDefense frame 0
    {1U, 2518U, 2U, 1024U, 1024U}, // TextureId::HeroicCapybara frame 0
}};

inline constexpr std::array<SceneAtlasTexture, 35U>
    kSceneAtlasTextures {{
    {}, // TextureId::None
    {512U, 512U, 512U, 512U, 0U, 1U, 1U, 1U}, // TextureId::Earth
    {512U, 512U, 512U, 512U, 1U, 1U, 1U, 1U}, // TextureId::Moon
    {512U, 512U, 512U, 512U, 2U, 1U, 1U, 1U}, // TextureId::Mars
    {1024U, 1024U, 1024U, 1024U, 3U, 1U, 1U, 1U}, // TextureId::RocketClosed
    {1024U, 128U, 128U, 128U, 4U, 8U, 1U, 8U}, // TextureId::Explosion
    {768U, 128U, 128U, 128U, 12U, 6U, 1U, 6U}, // TextureId::Thrust
    {512U, 512U, 512U, 512U, 18U, 1U, 1U, 1U}, // TextureId::MiningDrone
    {672U, 112U, 112U, 112U, 19U, 6U, 1U, 6U}, // TextureId::DrillBit
    {4096U, 576U, 1024U, 576U, 25U, 4U, 1U, 4U}, // TextureId::LocalSolarBackground
    {512U, 512U, 512U, 512U, 29U, 1U, 1U, 1U}, // TextureId::Mercury
    {512U, 512U, 512U, 512U, 30U, 1U, 1U, 1U}, // TextureId::Venus
    {512U, 512U, 512U, 512U, 31U, 1U, 1U, 1U}, // TextureId::Jupiter
    {512U, 512U, 512U, 512U, 32U, 1U, 1U, 1U}, // TextureId::Saturn
    {512U, 512U, 512U, 512U, 33U, 1U, 1U, 1U}, // TextureId::Uranus
    {512U, 512U, 512U, 512U, 34U, 1U, 1U, 1U}, // TextureId::Neptune
    {1254U, 1254U, 1254U, 1254U, 35U, 1U, 1U, 1U}, // TextureId::ArkOperational
    {1254U, 1254U, 1254U, 1254U, 36U, 1U, 1U, 1U}, // TextureId::ArkDamaged
    {1254U, 1254U, 1254U, 1254U, 37U, 1U, 1U, 1U}, // TextureId::OuterPlanet01
    {1254U, 1254U, 1254U, 1254U, 38U, 1U, 1U, 1U}, // TextureId::OuterPlanet02
    {1254U, 1254U, 1254U, 1254U, 39U, 1U, 1U, 1U}, // TextureId::OuterPlanet03
    {1254U, 1254U, 1254U, 1254U, 40U, 1U, 1U, 1U}, // TextureId::OuterPlanet04
    {1254U, 1254U, 1254U, 1254U, 41U, 1U, 1U, 1U}, // TextureId::OuterPlanet05
    {1254U, 1254U, 1254U, 1254U, 42U, 1U, 1U, 1U}, // TextureId::OuterPlanet06
    {1254U, 1254U, 1254U, 1254U, 43U, 1U, 1U, 1U}, // TextureId::OuterPlanet07
    {1254U, 1254U, 1254U, 1254U, 44U, 1U, 1U, 1U}, // TextureId::OuterPlanet08
    {1254U, 1254U, 1254U, 1254U, 45U, 1U, 1U, 1U}, // TextureId::OuterPlanet09
    {1024U, 1024U, 1024U, 1024U, 46U, 1U, 1U, 1U}, // TextureId::RocketOpen
    {512U, 512U, 512U, 512U, 47U, 1U, 1U, 1U}, // TextureId::MiniDroneMining
    {512U, 512U, 512U, 512U, 48U, 1U, 1U, 1U}, // TextureId::MiniDroneResource
    {512U, 512U, 512U, 512U, 49U, 1U, 1U, 1U}, // TextureId::MiniDroneSurvey
    {512U, 512U, 512U, 512U, 50U, 1U, 1U, 1U}, // TextureId::MiniDroneHazard
    {512U, 512U, 512U, 512U, 51U, 1U, 1U, 1U}, // TextureId::MiniDroneAttack
    {512U, 512U, 512U, 512U, 52U, 1U, 1U, 1U}, // TextureId::MiniDroneDefense
    {1024U, 1024U, 1024U, 1024U, 53U, 1U, 1U, 1U}, // TextureId::HeroicCapybara
}};

static_assert(kSceneAtlasTextures.size() == textureIndex(TextureId::Count));

} // namespace rocket
